from django.contrib import admin
from django.urls import path

from . import views
from .views import submit_survey_responses

urlpatterns = [
    # path('',views.home, name='home'),
    path('',views.home, name='home'),
    path('generatehealthcarequestions/', views.generate_healthcare_questions_json, name='generate_healthcare_questions_json'),
    path('storehealthcareanswers/',views.store_healthcare_answers, name='store_healthcare_answers'),
    path('hospitality_travel_questions/',views.generate_hospitality_travel_json, name='generate_hospitality_travel_json'),
    path('store_hospitality_travel_answers/', views.store_hospitality_travel_answers, name='store_hospitality_travel_answers'),
    path('generate_education_questions_json/',views.generate_education_questions_json, name='generate_education_questions_json'),
    path('generate_employee_satisfaction_questions_json/',views.generate_employee_satisfaction_questions_json, name='generate_employee_satisfaction_questions_json'),
    path('sentiment_analysis/', views.calculate_sentiment_percentage, name='sentiment_analysis'),
    path('survey_view/',views.survey_view, name='survey_view'),
    path('chat_with_gpt/', views.chat_with_gpt_view, name='chat_with_gpt'),
    path('my_view/', views.my_view_function, name='my_view'),   
    path('starter_temp/', views.starter_temp),
    path('maintenece/', views.maintence,name='maintain_page'),
    path('customer_satisfaction/', views.customer_satisfaction, name='customerSatisfaction'),
    # path('survey_preview/',views.survey_preview), 
    path('healthcarequestions/',views.healthcarequestions, name='healthcarequestions'), 
    path('builtwithscratch/', views.buildWithScratch, name='buildwithscratch'),
    path('buildwith_ai/', views.buildwithAi, name='buildwith_ai'),
    path('buildwith_ai/temp/', views.build_AI, name='buildwith_ai'),
    path('ai_preview/', views.ai_preview, name='ai_preview'),
    path('startfromtemplate/', views.startFromTemplate, name='startFromTemplate'),
    path('universityinstructor/', views.universityinstructor, name='universityInstructor'),
    path('eventfeedback/', views.eventfeedback, name='eventFeedback'),
    path('softwarefeedback/', views.softwarefeedback, name='softwareFeedback'),
    path('retailsurvey/', views.retailsurvey, name='retailSurvey'),
    path('volunteerfeedback/', views.volunteerfeedback, name='volunteerFeedback'),
    path('workfromhome/', views.workfromhome, name='workFromHome'),
    path('netpromotor/', views.netpromotor, name='netPromotor'),
    path('customerservice/', views.customerservice, name='customerService'),
    path('applicationexperience/', views.applicationexperience, name='applicationExperience'),
    path('businesstobusiness/', views.businesstobusiness, name='businessToBusiness'),
    path('brandawareness/', views.brandawareness, name='brandAwareness'),
    path('emailnewsletter/', views.emailnewsletter, name='emailNewsLetter'),
    path('employeeawardnomination/', views.employeeawardnomination, name='employeeAwardNomination'),
    path('competitivedifferentiation/', views.competitivedifferentiation, name='competitiveDifferentiation'),
    path('customerimpactsurvey/', views.customerimpactsurvey, name='customerImpactSurvey'),
    path('generalhighschoolsatisfaction/', views.generalhighschoolsatisfaction, name='generalHighSchoolSatisfaction'),
    path('k12parentsurvey/', views.k12parentsurvey, name='k12ParentSurvey'),
    path('k12distancelearning/', views.k12distancelearning, name='k12DistanceLearning'),
    path('quiz/', views.quiz, name='Quiz'),
    path('quiz01/', views.quiz01, name='QUIZ01'),
    path('alumni/', views.alumni, name='Almuni'),
    path('endurance/', views.endurance, name='enduranceFeedback'),
    path('eventplanning/',views.eventplanning, name='eventPlanning'),
    path('submit_survey_responses/', submit_survey_responses, name='submit_survey_responses'),
]       